-- ==============================================================================
-- TRAYMBHKAM TOUR AND TRAVELS (HARIDWAR) - SUPABASE INITIAL DATABASE SETUP
-- Paste this script into Supabase Dashboard -> SQL Editor -> Run
-- ==============================================================================

-- 1. LEADS TABLE
CREATE TABLE IF NOT EXISTS public.leads (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    destination TEXT,
    budget NUMERIC DEFAULT 0,
    advance_amount NUMERIC DEFAULT 0,
    travel_dates TEXT,
    pax_count TEXT,
    notes TEXT,
    status TEXT DEFAULT 'new_inquiry',
    source TEXT DEFAULT 'Manual / WhatsApp',
    assigned_to TEXT DEFAULT 'Mr. Gagandeep',
    unread_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. ITINERARIES TABLE
CREATE TABLE IF NOT EXISTS public.itineraries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    total_cost NUMERIC DEFAULT 0,
    document_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. VOUCHERS TABLE (HOTELS & TRANSPORT)
CREATE TABLE IF NOT EXISTS public.vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_type TEXT NOT NULL,
    guest_name TEXT,
    document_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. CLIENTS TABLE
CREATE TABLE IF NOT EXISTS public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT UNIQUE,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. INVOICES TABLE
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT,
    client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
    total_amount NUMERIC DEFAULT 0,
    document_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. VENDORS TABLE
CREATE TABLE IF NOT EXISTS public.vendors (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT,
    contact_person TEXT,
    phone TEXT,
    location TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. PAYABLES TABLE
CREATE TABLE IF NOT EXISTS public.payables (
    id TEXT PRIMARY KEY,
    vendor_id TEXT,
    amount NUMERIC DEFAULT 0,
    due_date DATE,
    status TEXT DEFAULT 'pending',
    booking_id TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    id TEXT PRIMARY KEY DEFAULT 'app_settings',
    openai_key TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Seed initial settings row if not present
INSERT INTO public.settings (id, openai_key)
VALUES ('app_settings', '')
ON CONFLICT (id) DO NOTHING;

-- ==============================================================================
-- ENABLE ROW LEVEL SECURITY (RLS) & ALLOW ANON/SERVICE OPERATIONS
-- ==============================================================================
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itineraries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vouchers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Create Open Access Policies for CRM Anon Key
CREATE POLICY "Allow public read-write for leads" ON public.leads FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for itineraries" ON public.itineraries FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for vouchers" ON public.vouchers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for clients" ON public.clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for invoices" ON public.invoices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for vendors" ON public.vendors FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for payables" ON public.payables FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);
